# Site settings
title: Thomas Matlock's Coding Journey 
header-img: img/home-bg.png
email: thomasmatlock1994@gmail.com
copyright_name: zep1994
description: > # this means to ignore newlines until "baseurl:"
  OO Ruby and SQL
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  zep1994
learn_profile: zep1994
email_username: thomasmatlock1994@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
