# Site settings
author: Thomas Matlock
title: Thomas Matlock's Coding Journey 
header-img: img/home-bg.png
email: snaxbags@protonmail.com
copyright_name: Thomas Matlock
description: > # this means to ignore newlines until "baseurl:"
  Ruby on Rails, Javascript, AJAX,  SQL
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: Snaxbags
github_username:  zep1994

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
